### ISSUE TITLE
database is locked and crash

### ISSUE THREAD

**Issue by aliafshany** [NidukaAkalanka/x-ui-english#143]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

i have a few hundred user on one of my ports and the thing is, this script casually crashes.
i am definitely certain that none of the email ids are similar, all of them are unique.
but still I get this error.
i really don't know what to do.
database gets locked and then x-ui crashes. reinstalling the x-ui won't help at all. i still get that error.
please do investigate this. i have to manually transfer all the users I have to another server. that costs me a lot actually.

FYI I enter this command but no luck at all:
`sudo chown root /etc/x-ui-english/x-ui-english.db`

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/40741745/216844912-fadbd8b9-94c5-41f0-a213-41a55d9085b4.png">

here is the log using this command:
`https://github.com/NidukaAkalanka/x-ui-english/issues/92`

### Version of x-ui

<details>

```console
$ x-ui version
# 0.2.1.2
```

</details>

### x-ui log or xray log

Feb 05 19:15:56 srv1674758352.hosttoname.com systemd[1]: Started x-ui Service.
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 x-ui-english 0.2.1.2
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - web server run https on [::]:7890
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User iy73vkx00@39 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User 1lt6lv5@41 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User dcbjlv8w7@42 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User fzgxfe5gce@43 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User wmjm92@44 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User xr6htg7ie@45 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User lg3ml6@46 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User cyi576gg@47 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User mhjbzj9m@48 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User exwylnb9p@49 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User qen22ntj@50 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User sifr4z@kasiri-0 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User 5qoywf@143 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User npc70gi@162 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User l58yzf@243 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User dqz1s0riu@386 due the expire or traffic limit
Feb 05 19:15:57 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:15:57 INFO - Remove Inbound User esgzhq57@David1 due the expire or traffic limit
Feb 05 19:31:56 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:31:56 http: TLS handshake error from 167.235.78.85:42536: read tcp 46.249.49.206:7890->167.235.78.85:42536: read: connection reset by peer
Feb 05 19:34:12 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:34:12 http: TLS handshake error from 167.235.78.85:60032: EOF
Feb 05 19:34:30 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:34:30 http: TLS handshake error from 167.235.78.85:42230: EOF
Feb 05 19:35:43 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:35:43 http: TLS handshake error from 167.235.78.85:55040: EOF
Feb 05 19:39:03 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:03 WARNING - disable invalid Client err: database is locked
Feb 05 19:39:03 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:03 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:39:08 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:08 WARNING - disable invalid inbounds err: database is locked
Feb 05 19:39:08 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:08 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Feb 05 19:39:19 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:19 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:39:28 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:28 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:39:29 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:29 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:39:33 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:33 WARNING - disable invalid Client err: database is locked
Feb 05 19:39:38 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:38 WARNING - disable invalid inbounds err: database is locked
Feb 05 19:39:39 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:39 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:39:48 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:48 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:39:53 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:39:53 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:40:01 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:01 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:40:03 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:03 WARNING - disable invalid Client err: database is locked
Feb 05 19:40:04 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:04 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:40:08 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:08 WARNING - disable invalid inbounds err: database is locked
Feb 05 19:40:09 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:09 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:40:14 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:14 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:40:18 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:18 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:40:21 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:21 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Feb 05 19:40:28 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:28 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:40:29 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:29 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Feb 05 19:40:33 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:33 WARNING - disable invalid Client err: database is locked
Feb 05 19:40:38 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:38 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:40:38 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:38 WARNING - disable invalid inbounds err: database is locked
Feb 05 19:40:39 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:39 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: 2023/02/05 19:40:47 WARNING - client ip job err: database is locked
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0xae86ab]
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: goroutine 48349 [running]:
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: x-ui/web/job.updateInboundClientIps(0xc000482ed0, {0xc00094dca5, 0xa}, {0xc0006b1a20?, 0x2, 0x2})
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:195 +0x24b
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: x-ui/web/job.processLogFile()
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:100 +0x40a
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: x-ui/web/job.(*CheckClientIpJob).Run(0xc0004db7d0?)
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:34 +0x65
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]: created by github.com/robfig/cron/v3.(*Cron).startJob
Feb 05 19:40:47 srv1674758352.hosttoname.com x-ui[668]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
Feb 05 19:40:47 srv1674758352.hosttoname.com systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 05 19:40:47 srv1674758352.hosttoname.com systemd[1]: x-ui.service: Failed with result 'exit-code'.
Feb 05 19:40:47 srv1674758352.hosttoname.com systemd[1]: x-ui.service: Consumed 59min 11.340s CPU time.
-- Boot 04ec8897dae84d2f919089f3ab8b9e91 --
Feb 05 19:49:26 srv1674758352.hosttoname.com systemd[1]: Started x-ui Service.
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 x-ui-english 0.2.1.2
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - web server run https on [::]:7890
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User iy73vkx00@39 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User 1lt6lv5@41 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User dcbjlv8w7@42 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User fzgxfe5gce@43 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User wmjm92@44 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User xr6htg7ie@45 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User lg3ml6@46 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User cyi576gg@47 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User mhjbzj9m@48 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User exwylnb9p@49 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User qen22ntj@50 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User sifr4z@kasiri-0 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User 5qoywf@143 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User npc70gi@162 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User l58yzf@243 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User dqz1s0riu@386 due the expire or traffic limit
Feb 05 19:49:27 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:49:27 INFO - Remove Inbound User esgzhq57@David1 due the expire or traffic limit
Feb 05 19:50:18 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:18 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Feb 05 19:50:33 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:33 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:50:33 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:33 WARNING - disable invalid Client err: database is locked
Feb 05 19:50:38 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:38 WARNING - add traffic failed: database is locked; no valid transaction; no valid transaction
Feb 05 19:50:38 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:38 WARNING - disable invalid inbounds err: database is locked
Feb 05 19:50:38 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:38 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Feb 05 19:50:46 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:46 WARNING - AddClientTraffic update data  UNIQUE constraint failed: client_traffics.email
Feb 05 19:50:48 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:48 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:50:58 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:50:58 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:51:03 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:03 WARNING - disable invalid Client err: database is locked
Feb 05 19:51:08 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:08 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:51:08 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:08 WARNING - disable invalid inbounds err: database is locked
Feb 05 19:51:09 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:09 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:51:18 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:18 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:51:19 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:19 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:51:28 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:28 WARNING - add traffic failed: database is locked; no valid transaction; no valid transaction
Feb 05 19:51:29 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:29 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:51:37 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:37 WARNING - disable invalid Client err: database is locked
Feb 05 19:51:38 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:38 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:51:42 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:42 WARNING - disable invalid inbounds err: database is locked
Feb 05 19:51:42 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:42 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:51:48 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:48 WARNING - add traffic failed: database is locked; no valid transaction
Feb 05 19:51:53 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:51:53 WARNING - AddClientTraffic update data  database is locked
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: 2023/02/05 19:52:13 WARNING - client ip job err: database is locked
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0xae86ab]
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: goroutine 2071 [running]:
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: x-ui/web/job.updateInboundClientIps(0xc000a840c0, {0xc0006f0391, 0xc}, {0xc0009e7a50?, 0x1, 0x1})
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:195 +0x24b
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: x-ui/web/job.processLogFile()
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:100 +0x40a
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: x-ui/web/job.(*CheckClientIpJob).Run(0x0?)
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]:         /home/runner/work/x-ui-english.dev/x-ui-english.dev/web/job/check_clinet_ip_job.go:34 +0x65
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: github.com/robfig/cron/v3.(*Cron).startJob.func1()
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]: created by github.com/robfig/cron/v3.(*Cron).startJob
Feb 05 19:52:13 srv1674758352.hosttoname.com x-ui[672]:         /home/runner/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
Feb 05 19:52:13 srv1674758352.hosttoname.com systemd[1]: x-ui.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 05 19:52:13 srv1674758352.hosttoname.com systemd[1]: x-ui.service: Failed with result 'exit-code'.
Feb 05 19:52:13 srv1674758352.hosttoname.com systemd[1]: x-ui.service: Consumed 6min 31.452s CPU time.
-- Boot 0b6e0082524e48f19eee2d360c05e883 --
Feb 05 20:42:50 srv1674758352.hosttoname.com systemd[1]: Started x-ui Service.
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 x-ui-english 0.2.1.2
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - web server run https on [::]:7890
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User iy73vkx00@39 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User 1lt6lv5@41 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User dcbjlv8w7@42 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User fzgxfe5gce@43 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User wmjm92@44 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User xr6htg7ie@45 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User lg3ml6@46 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User cyi576gg@47 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User mhjbzj9m@48 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User exwylnb9p@49 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User qen22ntj@50 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User sifr4z@kasiri-0 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User 5qoywf@143 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User npc70gi@162 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User l58yzf@243 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User dqz1s0riu@386 due the expire or traffic limit
Feb 05 20:42:51 srv1674758352.hosttoname.com x-ui[673]: 2023/02/05 20:42:51 INFO - Remove Inbound User esgzhq57@David1 due the expire or traffic limit
^C
root@srv1674758352:~# sudo systemctl status x-ui
● x-ui.service - x-ui Service
     Loaded: loaded (/etc/systemd/system/x-ui.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-02-05 20:42:50 UTC; 6min ago
   Main PID: 673 (x-ui)
      Tasks: 26 (limit: 4655)
     Memory: 448.7M
        CPU: 10min 24.025s
     CGroup: /system.slice/x-ui.service
             ├─ 673 /usr/local/x-ui/x-ui
             ├─ 699 bin/xray-linux-amd64 -c bin/config.json -restrictedIPsPath ./bin/blockedIPs
             ├─2377 bash -c "ss --tcp | grep -E '((127\\.0\\.0\\.1)|(.46\\.249\\.49\\.206))'| awk '{if(\$1==\"ESTAB\") print \$4,\$5;}'" "| s>
             └─2378 ss --tcp

**Comment by aliafshany** [comment]
@NidukaAkalanka it seems this error is related to these line of this link
https://github.com/NidukaAkalanka/x-ui-english/blob/main/web/job/check_clinet_ip_job.go#L34


Line 195 in the "x-ui/web/job.updateInboundClientIps" function
Line 100 in the "x-ui/web/job.processLogFile" function
Line 34 in the "x-ui/web/job.(*CheckClientIpJob).Run" function

an explantion from another expert:

> The error log suggests that the program is encountering a segmentation violation (SIGSEGV) and crashing. This usually occurs when the program tries to access a memory address that it is not authorized to access.
Based on the stack trace, the error appears to occur in the "x-ui/web/job.updateInboundClientIps" function at line 195. It would require further inspection of the code and its dependencies to determine the exact cause of the error and provide a solution.
It's also possible that the problem could be related to incorrect arguments being passed to the "updateInboundClientIps" function, or an issue with the data it's operating on.

**Comment by attacking6** [comment]
i have exact same issue

**Comment by amirparto1** [comment]
Same issue:

![Image](https://github.com/user-attachments/assets/c2f4e38c-b414-4f3d-9c84-c10277972301)
